development:
  clients:
    default:
      uri: 'mongodb://<%= ENV['MONGO_USER'] %>:<%= ENV['MONGO_PASSWORD'] %>@<%= ENV['MONGO_LOCATION'] %>:27017/parking_control_<%= ENV['SINATRA_ENV'] %>'
      options:
        write:
          w: 1
        auth_source: admin
